# Describes the format for the service calls

action_get_torrent_info:
  name: Get torrent info
  description: Returns detailed torrent information on a specific torrent (if hash is set) or all torrents
  fields:
    hash:
      name: hash
      description: The hash associated with the torrent that should be returned
      example: 0a861ed12bf4f16f67b9a747e149c7e6b1863e51
      required: false
      selector:
        text:
    status_filter:
      name: status_filter
      description: Optional status filter
      example: seeding
      required: false
      selector:
        select:
          options:
            - "all"
            - "downloading"
            - "seeding"
            - "completed"
            - "paused"
            - "stopped"
            - "active"
            - "inactive"
            - "resumed"
            - "running"
            - "stalled"
            - "stalled_uploading"
            - "stalled_downloading"
            - "checking"
            - "moving"
            - "errored"

action_pause_downloads:
  name: Pause torrent
  description: Pause a specific torrent (if hash is set) or all torrents
  fields:
    hash:
      name: hash
      description: The hash associated with the torrent that should be paused
      example: 0a861ed12bf4f16f67b9a747e149c7e6b1863e51
      required: false
      selector:
        text:

action_resume_downloads:
  name: Resume torrent
  description: Resume a specific torrent (if hash is set) or all torrents)
  fields:
    hash:
      name: hash
      description: The hash associated with the torrent that should be resumed
      example: 0a861ed12bf4f16f67b9a747e149c7e6b1863e51
      required: false
      selector:
        text:

action_delete_torrent:
  name: Delete torrent
  description: Delete a specific torrent and optionally its associated files
  fields:
    hash:
      name: hash
      description: The hash associated with the torrent that should be deleted
      example: 0a861ed12bf4f16f67b9a747e149c7e6b1863e51
      required: true
      selector:
        text:
    delete_files:
      name: delete_files
      description: Set to True to also delete the torrent's files
      example: True 
      required: true
      selector:
        boolean:

action_service_shutdown:
    name: Shut down qBittorrent
    description: Attempts to shut down the qBitorrent client
